/**
 ******************************************************************************
 * @addtogroup OpenPilotModules OpenPilot Modules
 * @{
 * @addtogroup Sensors
 * @brief Acquires sensor data
 * @{
 *
 * @file       sensors.c
 * @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2015.
 * @brief      Module to handle fetch and preprocessing of sensor data
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 ******************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

/**
 * Input objects: None, takes sensor data via pios
 * Output objects: @ref GyroSensor @ref AccelSensor @ref MagSensor
 *
 * The module executes in its own thread.
 *
 * UAVObjects are automatically generated by the UAVObjectGenerator from
 * the object definition XML file.
 *
 * Modules have no API, all communication to other modules is done through UAVObjects.
 * However modules may use the API exposed by shared libraries.
 * See the OpenPilot wiki for more details.
 * http://www.openpilot.org/OpenPilot_Application_Architecture
 *
 */

#include <openpilot.h>
#include <pios_sensors.h>
#include <barosensor.h>

#include "alarms.h"

#include <mathmisc.h>
#include <taskinfo.h>
#include <pios_math.h>
#include <pios_constants.h>
#include <CoordinateConversions.h>
#include <pios_board_info.h>
#include <string.h>

// Private constants
#define STACK_SIZE_BYTES         800
#define TASK_PRIORITY            (tskIDLE_PRIORITY + 1)

static const TickType_t sensor_period_ticks = ((uint32_t)1000.0f / PIOS_SENSOR_RATE) / portTICK_RATE_MS;

#define MAX_SENSOR_DATA_SIZE (sizeof(PIOS_SENSORS_1Axis_SensorsWithTemp))
typedef struct {
    PIOS_SENSORS_1Axis_SensorsWithTemp sensorSample1Axis;
} sensor_data;

// Private functions
static void SensorsTask(void *parameters);

static void processSamples1d(PIOS_SENSORS_1Axis_SensorsWithTemp *sample, const PIOS_SENSORS_Instance *sensor);
static void handleBaro(float sample, float temperature);

// Private variables
static sensor_data *source_data;
static xTaskHandle sensorsTaskHandle;

/**
 * Initialise the module.  Called before the start function
 * \returns 0 on success or -1 if initialisation failed
 */
int32_t SensorsInitialize(void)
{
    source_data = (sensor_data *)pios_malloc(MAX_SENSOR_DATA_SIZE);
    BaroSensorInitialize();
	AlarmsInitialize();

    return 0;
}

/**
 * Start the task.  Expects all objects to be initialized by this point.
 * \returns 0 on success or -1 if initialisation failed
 */
int32_t SensorsStart(void)
{
    // Start main task
    xTaskCreate(SensorsTask, "Sensors", STACK_SIZE_BYTES / 4, NULL, TASK_PRIORITY, &sensorsTaskHandle);
    return 0;
}

MODULE_INITCALL(SensorsInitialize, SensorsStart);

/**
 * The sensor task.  This polls the gyros at 500 Hz and pumps that data to
 * stabilization and to the attitude loop
 *
 */
static void SensorsTask(__attribute__((unused)) void *parameters)
{
    portTickType lastSysTime;
    const PIOS_SENSORS_Instance *sensors_list = PIOS_SENSORS_GetList();
    PIOS_SENSORS_Instance *sensor;

    AlarmsClear(SYSTEMALARMS_ALARM_SENSORS);

    // Test sensors
    bool sensors_test = true;
    uint8_t count     = 0;
    LL_FOREACH((PIOS_SENSORS_Instance *)sensors_list, sensor) {
        sensors_test &= PIOS_SENSORS_Test(sensor);
        count++;
    }

    if (!sensors_test) {
        AlarmsSet(SYSTEMALARMS_ALARM_SENSORS, SYSTEMALARMS_ALARM_CRITICAL);
        while (1) {
            vTaskDelay(10);
        }
    }

    // Main task loop
    lastSysTime = xTaskGetTickCount();

    while (1) {
        // TODO: add timeouts to the sensor reads and set an error if the fail
        LL_FOREACH((PIOS_SENSORS_Instance *)sensors_list, sensor) {
            // we will wait on the sensor that's marked as primary( that means the sensor with higher sample rate)
            if (sensor->driver->is_polled){
                if (PIOS_SENSORS_Poll(sensor)) {
                    PIOS_SENSOR_Fetch(sensor, (void *)source_data, sizeof(source_data));
                    if (sensor->type & PIOS_SENSORS_TYPE_1AXIS_BARO) {
                        processSamples1d(&source_data->sensorSample1Axis, sensor);
                    }
                }
            }
        }
        vTaskDelayUntil(&lastSysTime, sensor_period_ticks);
    }
}

static void processSamples1d(PIOS_SENSORS_1Axis_SensorsWithTemp *sample, const PIOS_SENSORS_Instance *sensor)
{
    switch (sensor->type) {
    case PIOS_SENSORS_TYPE_1AXIS_BARO:
        handleBaro(sample->sample, sample->temperature);
        return;
    }
}

static void handleBaro(float sample, float temperature)
{
    float altitude = 44330.0f * (1.0f - powf((sample) / PIOS_CONST_MKS_STD_ATMOSPHERE_F, (1.0f / 5.255f)));

    BaroSensorData data;
    data.Altitude    = altitude;
    data.Temperature = temperature / 100.0f;
    data.Pressure    = sample / 100.0f;
    // Update the BasoSensor UAVObject
    BaroSensorSet(&data);
}

/**
 * @}
 * @}
 */
